Repository ehddbs4521/KB_6_TEAM_GIT_PRACTICE, pull requests merged in 2025-03, with the labels that each got.

#5 [FEAT] 채팅 방 html 기본 세팅
  pages/chat/chat.html
Labels: feat

#9 [FEAT] 홈 화면 기본 세팅
  pages/home/home.css
  pages/home/home.html
Labels: feat

#13 [FEAT] 채팅 이미지 스타일 꾸미기
  pages/chat/chat.css
  pages/chat/chat.html
  pages/chat/person1.jpeg
  pages/chat/person2.jpg
  pages/chat/person3.jpeg
Labels: feat

#17 [REFACTOR] 채팅방 간격 증가
  pages/chat/chat.css
Labels: refactor

#12 [FEAT] 커뮤니티 화면 기본 세팅
  Desert.jpg
  pages/local-life/localLife.html
Labels: feat

#16 [FEAT] 나의 당근 화면 구현
  pages/my/my.css
  pages/my/my.html
Labels: feat

#21 [REFACTOR] 나의 당근 연결
  index.html
Labels: refactor

#23 [DESIGN] 홈 화면 디자인 수정
  pages/home/home.html
Labels: enhancement

#24 [FEAT] index.html에 채팅방 링크 추가
  index.html
Labels: feat

#26 [FEAT] 홈 <-> index 링크 연결
  index.html
Labels: feat
